"""Builds data/cb/meetings.yaml from the official calendar pages (parsers in `calendar.py`), the FF decision days of the
ECB meetings already held (the ECB page lists only the future) and the RBNZ published calendar (manual: the site is
bot-walled). Pure: the caller supplies the parsed pages; `scripts/cb_gen_meetings.py` does the fetching.

Row rules
  date / first_day  decision day; first day only for multi-day meetings (Fed, ECB, BoJ, RBA) - from the page; a past
                    ECB meeting (not on the page) uses the Wednesday before the decision.
  has_projections   the page's own flag where it states one (Fed asterisk, BoE / BoC MPR, BoJ Outlook Report), else the
                    bank's projection months from config (ECB, RBA, SNB, RBNZ MPS list).
  has_presser       every_meeting / quarterly banks: true; mpr_only (BoE): the projections flag.
  source            official (page) | ff (ECB, decision day only from FF rows) | manual (RBNZ).
  verified          the evidence date for an official row, false for ff / manual / dates the bank calls provisional.
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Optional

ORDER = ["USD", "EUR", "GBP", "JPY", "CAD", "AUD", "NZD", "CHF"]
MULTI_DAY = {"USD", "EUR", "JPY", "AUD"}
RANGE = (date(2026, 1, 1), date(2027, 12, 31))
CHF_FROM = date(2025, 9, 1)                     # the last 4 SNB decisions

BASIS = {
    "USD": "dates + projections (SEP asterisk) from the FOMC calendar page; presser: every meeting (config), the page announces it only for past/near meetings",
    "EUR": "decision dates from the ECB GC calendar page (it lists upcoming meetings only): 2026 meetings already held come from FF decision rows (source: ff, NOT official); presser from the page; projections derived (Mar/Jun/Sep/Dec staff projections, ECB practice, not stated on the page)",
    "GBP": "dates from the BoE MPC page (2026 confirmed, 2027 PROVISIONAL); projections = Monetary Policy Report days; presser = MPR days only (config)",
    "JPY": "dates + Outlook Report (projections) from the BoJ schedule page; presser: every meeting (config), not stated on the schedule page",
    "CAD": "dates + MPR from the BoC schedule page; presser at every decision (BoC blackout page)",
    "AUD": "two-day board meetings, decision on day 2; dates from the RBA schedule page; projections derived (Statement on Monetary Policy Feb/May/Aug/Nov, RBA practice); presser every meeting (config)",
    "NZD": "MANUAL: transcribed from the RBNZ release 'Monetary policy and OCR decision dates until February 2027' via web search (rbnz.govt.nz is behind a Cloudflare challenge); MPS = projections; presser 15:00 NZ (config, unverified). Dates after 2027-02-17 not published yet",
    "CHF": "dates from the SNB decisions archive (past) and event schedule (upcoming); quarterly assessment with conditional inflation forecast and press conference every time",
}

HEADER = [
    "# Monetary-policy meetings 2026-2027. GENERATED by scripts/cb_gen_meetings.py from the official calendar pages - do not edit",
    "# by hand (src/cb_sources/meetings.py holds the rules; the weekly check in --status warns when a page drifts).",
    "#",
    "#   date            decision day (last day of a two-day meeting).",
    "#   first_day       first day of a multi-day meeting (Fed, ECB, BoJ, RBA), from the official calendar page; absent for one-day",
    "#                   meetings. Past ECB meetings (not on the page) use the Wednesday before the decision (source ff, unverified).",
    "#   has_projections the meeting publishes the bank's own projections (Fed SEP, ECB staff, BoE/BoC MPR, BoJ Outlook,",
    "#                   RBA SMP, RBNZ MPS, SNB conditional forecast).",
    "#   has_presser     press conference on decision day (transcript/video expected).",
    "#   source          official = date read from the bank's calendar page | ff = decision day seen only in FF rows",
    "#                   (not official; confirm) | manual = hand-transcribed (RBNZ site is bot-walled).",
    "#   verified        date on which the decision DATE was matched to its source; false = not verified against",
    "#                   an official page (also for dates the bank itself calls provisional: BoE 2027). The two flags",
    "#                   come from the page where it states them, otherwise they are derived (basis per bank below);",
    "#                   `verified` does not vouch for derived flags.",
    "#",
    "# RBNZ stays manual (data/cb/manual/rbnz.yaml) until the February 2027 release of the 2027 dates.",
    "",
]


def in_scope(bank: str, d: date) -> bool:
    return RANGE[0] <= d <= RANGE[1] or (bank == "CHF" and d >= CHF_FROM)


def _has_presser(banks: dict, bank: str, projections: bool) -> bool:
    return projections if banks[bank]["conference"]["held"] == "mpr_only" else True


def build_rows(bank: str, page: list, banks: dict, evidence: date, ff_days: Optional[list] = None,
               manual: Optional[list] = None) -> list:
    """[(date, first_day | None, has_projections, has_presser, source, verified)] for one bank, sorted by date."""
    months = set(banks[bank]["projections"]["months"])
    rows: dict = {}

    def add(d, first_day, proj, source, verified):
        rows[d] = (d, first_day if bank in MULTI_DAY else None, proj, _has_presser(banks, bank, proj), source, verified)

    if bank == "NZD":                                               # manual list, never a page
        for m in manual or []:
            add(m["date"], None, bool(m["has_projections"]), "manual", False)
    else:
        for m in page:
            if not in_scope(bank, m["date"]):
                continue
            proj = m["has_projections"] if m.get("has_projections") is not None else m["date"].month in months
            add(m["date"], m.get("first_day"), bool(proj), "official", False if m.get("provisional") else evidence)
    if bank == "EUR":                                               # meetings already held: only FF knows them
        first_on_page = min((d for d in rows), default=None)
        for d in sorted(set(ff_days or [])):
            if d >= RANGE[0] and (first_on_page is None or d < first_on_page) and d not in rows:
                add(d, d - timedelta(days=1), d.month in months, "ff", False)
    return [rows[d] for d in sorted(rows)]


def render(rows_by_bank: dict, evidence: date) -> str:
    lines = list(HEADER) + [
        f"meta: {{version: 2, evidence_date: {evidence.isoformat()}, range: [{RANGE[0].isoformat()}, {RANGE[1].isoformat()}], "
        f"extra: {{CHF: \"from {CHF_FROM.isoformat()} (the last 4 SNB decisions)\"}}}}",
        "", "meetings:"]
    for bank in ORDER:
        lines.append(f"  {bank}:     # {BASIS[bank]}")
        for d, fd, proj, pres, src, ver in rows_by_bank[bank]:
            fdt = f" first_day: {fd.isoformat()}," if fd else ""
            v = ver.isoformat() if isinstance(ver, date) else "false"
            lines.append(f"    - {{date: {d.isoformat()},{fdt} has_projections: {str(proj).lower()}, "
                         f"has_presser: {str(pres).lower()}, source: {src}, verified: {v}}}")
    return "\n".join(lines) + "\n"


def build(parsed: dict, banks: dict, evidence: date, ff_ecb_days: Optional[list] = None,
          rbnz_manual: Optional[list] = None) -> str:
    """`parsed` = {bank: parsed page meetings} for USD, EUR, GBP, JPY, CAD, AUD, CHF."""
    return render({b: build_rows(b, parsed.get(b, []), banks, evidence, ff_ecb_days, rbnz_manual) for b in ORDER}, evidence)
