"""Estimate the BKBM - OCR spread for NZD and write config/cb_nzd_spread.yaml.

    python scripts/cb_nzd_bkbm_spread.py [--start 2015-01] [--out config/cb_nzd_spread.yaml] [--dry-run]

3M NZ interbank rate (OECD, monthly): FRED IR3TIB01NZM156N through the keyless fredgraph CSV the collector already uses;
OCR: BIS WS_CBPOL (NZ, daily) through the same API as cb_official. Rule in src/cb_compute/nzd_spread.py (median of 3M - OCR
over the months with no OCR change in the month and the 3 after it). Run by hand when `--status` says the file is older than
100 days; the engine reads the file through src/cb_loader.py.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date, datetime, timezone
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.cb_compute.nzd_spread import bkbm_ocr_spread              # noqa: E402
from src.cb_sources.base import NON_BROWSER_UA, HttpSource         # noqa: E402
from src.cb_sources.official import load_official, parse_bis, parse_fred   # noqa: E402

FRED_ID = "IR3TIB01NZM156N"
OUT = ROOT / "config" / "cb_nzd_spread.yaml"


def fetch(since: date) -> tuple:
    prov = load_official()["providers"]
    http = HttpSource()
    fred_url = prov["fred"]["url"].format(key=FRED_ID, since=since.isoformat())
    bis_url = prov["bis"]["url"].format(areas="NZ", since=since.isoformat())
    r1, _, _ = http.get_url(fred_url, ua=NON_BROWSER_UA)
    if r1 is None:
        raise SystemExit(f"FRED {FRED_ID}: {http.last_status} {http.last_note}")
    r2, _, _ = http.get_url(bis_url)
    if r2 is None:
        raise SystemExit(f"BIS WS_CBPOL NZ: {http.last_status} {http.last_note}")
    return parse_fred(r1.text, since), parse_bis(r2.text, since).get("NZ", []), fred_url, bis_url


def document(res, fred_url: str, bis_url: str, today: date) -> dict:
    return {
        "value_bp": round(res.value_bp, 1), "n_months": res.n_months, "window": list(res.window),
        "iqr_bp": [round(x, 1) for x in res.iqr_bp], "computed_on": today,
        "rule": "median over months of (3M NZ interbank, monthly) - (mean OCR of the month); only months with no OCR change in the month "
                "and the 3 months after it (src/cb_compute/nzd_spread.py)",
        "sources": {"rate_3m": {"series": f"FRED {FRED_ID} (OECD, 3-month interbank rate, NZ, monthly)", "url": fred_url},
                    "ocr": {"series": "BIS WS_CBPOL D.NZ (Official Cash Rate, daily)", "url": bis_url}},
        "months": [{"month": m, "diff_bp": round(x, 1)} for m, x in res.months],
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--start", default="2015-01")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args(argv)
    y, m = (int(x) for x in a.start.split("-"))
    m3, ocr, fu, bu = fetch(date(y, m, 1))
    res = bkbm_ocr_spread(m3, ocr, (y, m))
    if res.value_bp is None:
        raise SystemExit(f"no spread: {res.reason}")
    doc = document(res, fu, bu, datetime.now(timezone.utc).date())
    head = "# BKBM - OCR spread for NZD (estimate, not a daily observation). GENERATED by scripts/cb_nzd_bkbm_spread.py - do not edit by hand.\n"
    text = head + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=200)
    print(f"spread {doc['value_bp']} bp, {doc['n_months']} months, window {doc['window'][0]}..{doc['window'][1]}, IQR {doc['iqr_bp']}")
    if not a.dry_run:
        a.out.write_text(text)
        print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
